// @babel/parser 用来将JS代码转换成AST，
// @babel/traverse 用来遍历AST中的节点，
// @babel/types 用来判断节点类型、生成新的节点等，
// @babel/generator用来把AST转换成JS代码，
// AST处理JS文件的基本步骤为：首先读取JS文件，解析成AST，再对节点进行一系列的增、删、改、查操作，
// 接着生成JS代码，最后保存到新文件中。

const fs = require("fs/promises");
const path = require("path");
const parser = require("@babel/parser");
const traverse = require("@babel/traverse").default;
const generator = require("@babel/generator").default;
const type = require("@babel/types");


let ftosMap = new Map([
    [
        "1:3589",
        "stringify"
    ],
    [
        "1:3628",
        "parse"
    ],
    [
        "1:3651",
        "parse"
    ],
    [
        "1:4936",
        "log"
    ],
    [
        "1:4947",
        "我盯着你呢小子"
    ],
    [
        "1:6050",
        "sfGUa"
    ],
    [
        "1:6068",
        "(((.+)+)+)"
    ],
    [
        "1:6135",
        "YmpED"
    ],
    [
        "1:6153",
        "0|4|2|1|3"
    ],
    [
        "1:6533",
        "SZkWU"
    ],
    [
        "1:6664",
        "return (fu"
    ],
    [
        "1:6681",
        "nction() "
    ],
    [
        "1:6706",
        "{}.constru"
    ],
    [
        "1:6723",
        "ctor(\"retu"
    ],
    [
        "1:6740",
        "rn this\")("
    ],
    [
        "1:6890",
        "QOSBH"
    ],
    [
        "1:6924",
        "yzmFD"
    ],
    [
        "1:6942",
        "bRbsQ"
    ],
    [
        "1:6982",
        "info"
    ],
    [
        "1:7000",
        "exception"
    ],
    [
        "1:7018",
        "trace"
    ],
    [
        "1:7363",
        "yaDgC"
    ],
    [
        "1:7559",
        "3|1|0|4|2"
    ],
    [
        "1:10139",
        "kKbOH"
    ],
    [
        "1:10299",
        "1|4|0|2|3"
    ],
    [
        "1:12956",
        "FYKEm"
    ],
    [
        "1:13156",
        "0123456789"
    ],
    [
        "1:13260",
        "xialuo"
    ],
    [
        "1:13321",
        "xxoo"
    ],
    [
        "1:13339",
        "Jytnr"
    ],
    [
        "1:13519",
        "QpPKj"
    ],
    [
        "1:13704",
        "jeVyI"
    ],
    [
        "1:13828",
        "feEbr"
    ],
    [
        "1:14003",
        "JRVIF"
    ],
    [
        "1:14283",
        "AEPZB"
    ],
    [
        "1:14469",
        "GSknF"
    ],
    [
        "1:14193",
        "apply"
    ],
    [
        "1:14358",
        "toString"
    ],
    [
        "1:14371",
        "search"
    ],
    [
        "1:14415",
        "constructo"
    ],
    [
        "1:14445",
        "ivsVn"
    ],
    [
        "1:14534",
        "gTJhf"
    ],
    [
        "1:15142",
        "MaJwA"
    ],
    [
        "1:16339",
        "uLzGT"
    ],
    [
        "1:15221",
        "OtbMK"
    ],
    [
        "1:15241",
        "hBnHQ"
    ],
    [
        "1:15261",
        "hBnHQ"
    ],
    [
        "1:16178",
        "YEYja"
    ],
    [
        "1:16190",
        "HtzRn"
    ],
    [
        "1:15107",
        "rlniE"
    ],
    [
        "1:16248",
        "apply"
    ],
    [
        "1:16680",
        "UNyEI"
    ],
    [
        "1:16865",
        "{}.constru"
    ],
    [
        "1:16882",
        "ctor(\"retu"
    ],
    [
        "1:16892",
        "rn this\")("
    ],
    [
        "1:16934",
        "FgysG"
    ],
    [
        "1:16954",
        "XSfXk"
    ],
    [
        "1:17118",
        "YHyur"
    ],
    [
        "1:16645",
        "rlniE"
    ],
    [
        "1:17158",
        "QuPGS"
    ],
    [
        "1:17178",
        "MWlQH"
    ],
    [
        "1:17189",
        "trMcG"
    ],
    [
        "1:16443",
        "JzUaT"
    ],
    [
        "1:17204",
        "pxZXD"
    ],
    [
        "1:17226",
        "hlHgL"
    ],
    [
        "1:17246",
        "IVprD"
    ],
    [
        "1:17277",
        "xwTEy"
    ],
    [
        "1:16820",
        "sXudK"
    ],
    [
        "1:16752",
        "sXudK"
    ],
    [
        "1:16510",
        "gelEG"
    ],
    [
        "1:17621",
        "console"
    ],
    [
        "1:17641",
        "console"
    ],
    [
        "1:17659",
        "log"
    ],
    [
        "1:17671",
        "MhZul"
    ],
    [
        "1:17684",
        "UOiiP"
    ],
    [
        "1:17695",
        "error"
    ],
    [
        "1:17714",
        "jUpNr"
    ],
    [
        "1:17725",
        "table"
    ],
    [
        "1:17737",
        "ZErCv"
    ],
    [
        "1:17787",
        "tBmhV"
    ],
    [
        "1:17828",
        "constructo"
    ],
    [
        "1:17856",
        "bind"
    ],
    [
        "1:17896",
        "__proto__"
    ],
    [
        "1:17916",
        "bind"
    ],
    [
        "1:17939",
        "toString"
    ],
    [
        "1:17952",
        "toString"
    ],
    [
        "1:17963",
        "bind"
    ],
    [
        "1:42940",
        "eeee"
    ],
    [
        "1:44687",
        "enc"
    ],
    [
        "1:44705",
        "Utf8"
    ],
    [
        "1:44716",
        "parse"
    ],
    [
        "1:44734",
        "xxxxxxxxoo"
    ],
    [
        "1:44751",
        "oooooo"
    ],
    [
        "1:44775",
        "enc"
    ],
    [
        "1:44801",
        "parse"
    ],
    [
        "1:44812",
        "0123456789"
    ],
    [
        "1:44822",
        "ABCDEF"
    ],
    [
        "1:45470",
        "MRVhk"
    ],
    [
        "1:45710",
        "nFPkV"
    ],
    [
        "1:45728",
        "Mrtpk"
    ],
    [
        "1:45750",
        "ajax"
    ],
    [
        "1:45793",
        "Intercepto"
    ],
    [
        "1:46167",
        "addRespons"
    ],
    [
        "1:49190",
        "addRequest"
    ],
    [
        "1:49200",
        "Intercepto"
    ],
    [
        "1:45996",
        "jvuLF"
    ],
    [
        "1:46009",
        "gtugH"
    ],
    [
        "1:46041",
        "push"
    ],
    [
        "1:49650",
        "addRespons"
    ],
    [
        "1:46290",
        "JwMph"
    ],
    [
        "1:46305",
        "JwMph"
    ],
    [
        "1:46358",
        "push"
    ],
    [
        "1:50487",
        "Error fetc"
    ],
    [
        "1:50555",
        "json"
    ],
    [
        "1:50580",
        "page"
    ],
    [
        "1:50635",
        "toString"
    ],
    [
        "1:50678",
        "em-detail/"
    ],
    [
        "1:50705",
        "/data/?"
    ],
    [
        "1:50735",
        "syPwG"
    ],
    [
        "1:50759",
        "aGcCj"
    ],
    [
        "1:47131",
        "VSCiD"
    ],
    [
        "1:47159",
        "fZItm"
    ],
    [
        "1:47187",
        "forEach"
    ],
    [
        "1:49339",
        "xxoo"
    ],
    [
        "1:49367",
        "getTime"
    ],
    [
        "1:49408",
        "xialuo"
    ],
    [
        "1:43294",
        "dFbAj"
    ],
    [
        "1:44183",
        "hWOyw"
    ],
    [
        "1:44203",
        "hWOyw"
    ],
    [
        "1:43259",
        "GxadT"
    ],
    [
        "1:44577",
        "NmvPz"
    ],
    [
        "1:44599",
        "LIAXz"
    ],
    [
        "1:43414",
        "VJfjK"
    ],
    [
        "1:40570",
        "NUMzD"
    ],
    [
        "1:40601",
        "bVPIz"
    ],
    [
        "1:40622",
        "pDFRR"
    ],
    [
        "1:39386",
        "FYKEm"
    ],
    [
        "1:39400",
        "JTMeO"
    ],
    [
        "1:39438",
        "MKdaU"
    ],
    [
        "1:39458",
        "Qivrc"
    ],
    [
        "1:39471",
        "length"
    ],
    [
        "1:39614",
        "ElgMw"
    ],
    [
        "1:39636",
        "length"
    ],
    [
        "1:39730",
        "SFqDI"
    ],
    [
        "1:39781",
        "length"
    ],
    [
        "1:39885",
        "ldgNJ"
    ],
    [
        "1:39939",
        "ATgfM"
    ],
    [
        "1:39959",
        "RMtRl"
    ],
    [
        "1:39996",
        "charCodeAt"
    ],
    [
        "1:40009",
        "agDTJ"
    ],
    [
        "1:40061",
        "xBLkI"
    ],
    [
        "1:41125",
        "RAAYR"
    ],
    [
        "1:41164",
        "length"
    ],
    [
        "1:29311",
        "hCATJ"
    ],
    [
        "1:29329",
        "split"
    ],
    [
        "1:38485",
        "kWyrK"
    ],
    [
        "1:38540",
        "ATgfM"
    ],
    [
        "1:38583",
        "oeqKU"
    ],
    [
        "1:38635",
        "iyyac"
    ],
    [
        "1:38681",
        "MgQnQ"
    ],
    [
        "1:29672",
        "nYdpw"
    ],
    [
        "1:29687",
        "length"
    ],
    [
        "1:29759",
        "xWCBx"
    ],
    [
        "1:29776",
        "mzqLY"
    ],
    [
        "1:29793",
        "cxVKP"
    ],
    [
        "1:29821",
        "YsZWM"
    ],
    [
        "1:29838",
        "woOgP"
    ],
    [
        "1:29863",
        "XOzPD"
    ],
    [
        "1:29880",
        "pcSgc"
    ],
    [
        "1:29904",
        "vRFLm"
    ],
    [
        "1:29921",
        "RYPvZ"
    ],
    [
        "1:29979",
        "uYXIU"
    ],
    [
        "1:30028",
        "nVcFB"
    ],
    [
        "1:19058",
        "cXYer"
    ],
    [
        "1:18729",
        "rkFsh"
    ],
    [
        "1:18742",
        "ZkAHc"
    ],
    [
        "1:18762",
        "ZkAHc"
    ],
    [
        "1:18800",
        "wZgjz"
    ],
    [
        "1:18932",
        "wZgjz"
    ],
    [
        "1:18954",
        "wZgjz"
    ],
    [
        "1:18226",
        "xYhMS"
    ],
    [
        "1:18287",
        "PzEkN"
    ],
    [
        "1:18307",
        "SNWBG"
    ],
    [
        "1:18366",
        "Ojybj"
    ],
    [
        "1:18974",
        "MjdHC"
    ],
    [
        "1:18882",
        "zUuYu"
    ],
    [
        "1:18698",
        "TjHlL"
    ],
    [
        "1:30147",
        "aiUFT"
    ],
    [
        "1:30507",
        "esvjL"
    ],
    [
        "1:30539",
        "BobaN"
    ],
    [
        "1:30772",
        "SEQdv"
    ],
    [
        "1:31014",
        "JAskn"
    ],
    [
        "1:31040",
        "ZgGJm"
    ],
    [
        "1:31065",
        "HcUKR"
    ],
    [
        "1:31186",
        "CWDTd"
    ],
    [
        "1:31321",
        "AOOse"
    ],
    [
        "1:31446",
        "WySLl"
    ],
    [
        "1:31572",
        "ZgGJm"
    ],
    [
        "1:31608",
        "LsmzR"
    ],
    [
        "1:31758",
        "gNAzv"
    ],
    [
        "1:31883",
        "IAllZ"
    ],
    [
        "1:31999",
        "Tfgng"
    ],
    [
        "1:32114",
        "pcSgc"
    ],
    [
        "1:32180",
        "DSgnr"
    ],
    [
        "1:19173",
        "EZsLO"
    ],
    [
        "1:28929",
        "PzEkN"
    ],
    [
        "1:28949",
        "dDsTl"
    ],
    [
        "1:32413",
        "wlGJx"
    ],
    [
        "1:32609",
        "pPhYS"
    ],
    [
        "1:32628",
        "DWThP"
    ],
    [
        "1:32659",
        "SFbQB"
    ],
    [
        "1:32772",
        "XRnUX"
    ],
    [
        "1:32890",
        "ZSrHi"
    ],
    [
        "1:33123",
        "AAeOs"
    ],
    [
        "1:33155",
        "FDCwr"
    ],
    [
        "1:33402",
        "caQVd"
    ],
    [
        "1:33630",
        "mBvFI"
    ],
    [
        "1:33662",
        "bXtUP"
    ],
    [
        "1:33694",
        "BhPEA"
    ],
    [
        "1:33824",
        "ruQis"
    ],
    [
        "1:33947",
        "Tfgng"
    ],
    [
        "1:34065",
        "phRWA"
    ],
    [
        "1:34196",
        "JVTbo"
    ],
    [
        "1:34215",
        "esvjL"
    ],
    [
        "1:29045",
        "ITlWs"
    ],
    [
        "1:29058",
        "ITlWs"
    ],
    [
        "1:34447",
        "MQKYE"
    ],
    [
        "1:34557",
        "jDbag"
    ],
    [
        "1:34678",
        "mBvFI"
    ],
    [
        "1:34704",
        "WTxKj"
    ],
    [
        "1:34742",
        "WySLl"
    ],
    [
        "1:34862",
        "DSgnr"
    ],
    [
        "1:34990",
        "fpWGu"
    ],
    [
        "1:35113",
        "PhUUA"
    ],
    [
        "1:35251",
        "esvjL"
    ],
    [
        "1:35270",
        "xWCBx"
    ],
    [
        "1:35289",
        "PEeiy"
    ],
    [
        "1:35503",
        "vhAgy"
    ],
    [
        "1:35617",
        "BhPEA"
    ],
    [
        "1:35733",
        "cxVKP"
    ],
    [
        "1:35788",
        "llFgu"
    ],
    [
        "1:36030",
        "vhAgy"
    ],
    [
        "1:36277",
        "AoIih"
    ],
    [
        "1:36296",
        "RyzCJ"
    ],
    [
        "1:36315",
        "mBvFI"
    ],
    [
        "1:29162",
        "gNXxx"
    ],
    [
        "1:29225",
        "NqpiH"
    ],
    [
        "1:36631",
        "PbGJv"
    ],
    [
        "1:36759",
        "ZgGJm"
    ],
    [
        "1:36784",
        "uVbpb"
    ],
    [
        "1:36918",
        "iYCqt"
    ],
    [
        "1:37055",
        "KfUog"
    ],
    [
        "1:37285",
        "SySGO"
    ],
    [
        "1:37329",
        "hvVZK"
    ],
    [
        "1:37693",
        "vLLgy"
    ],
    [
        "1:37817",
        "OsmbE"
    ],
    [
        "1:37843",
        "bXtUP"
    ],
    [
        "1:37862",
        "FhDuY"
    ],
    [
        "1:37894",
        "SFbQB"
    ],
    [
        "1:38243",
        "ruQis"
    ],
    [
        "1:38369",
        "mGVbN"
    ],
    [
        "1:38391",
        "VYdcH"
    ],
    [
        "1:38421",
        "uLzGT"
    ],
    [
        "1:38876",
        "BzDwE"
    ],
    [
        "1:38922",
        "length"
    ],
    [
        "1:38980",
        "KEIUP"
    ],
    [
        "1:39059",
        "xYhMS"
    ],
    [
        "1:39119",
        "oeqKU"
    ],
    [
        "1:43347",
        "HXwzI"
    ],
    [
        "1:40283",
        "WiaXr"
    ],
    [
        "1:40305",
        "length"
    ],
    [
        "1:40344",
        "charCodeAt"
    ],
    [
        "1:40370",
        "charAt"
    ],
    [
        "1:40401",
        "HgmQz"
    ],
    [
        "1:40466",
        "charAt"
    ],
    [
        "1:49451",
        "headers"
    ],
    [
        "1:49475",
        "headers"
    ],
    [
        "1:49534",
        "&x="
    ],
    [
        "1:49589",
        "SHA256"
    ],
    [
        "1:49609",
        "QCqSI"
    ],
    [
        "1:47217",
        "bbcUL"
    ],
    [
        "1:5087",
        "Function(a"
    ],
    [
        "1:5104",
        "rguments[0"
    ],
    [
        "1:5178",
        "WKGcG"
    ],
    [
        "1:5203",
        "LoGxI"
    ],
    [
        "1:5834",
        "byRnv"
    ],
    [
        "1:5358",
        "hdpJc"
    ],
    [
        "1:5433",
        "acSgR"
    ],
    [
        "1:5466",
        "NTlHa"
    ],
    [
        "1:47312",
        "forEach"
    ],
    [
        "1:47343",
        "xzgxJ"
    ],
    [
        "1:46476",
        "ggZWw"
    ],
    [
        "1:49862",
        "rguments[0"
    ],
    [
        "1:49872",
        "]+\""
    ],
    [
        "1:50000",
        "KgyiJ"
    ],
    [
        "1:50120",
        "oBkKu"
    ],
    [
        "1:44891",
        "SZjeT"
    ],
    [
        "1:44938",
        "YRYfz"
    ],
    [
        "1:44949",
        "ypt"
    ],
    [
        "1:44990",
        "enc"
    ],
    [
        "1:45015",
        "parse"
    ],
    [
        "1:45042",
        "ciphertext"
    ],
    [
        "1:45069",
        "AES"
    ],
    [
        "1:45089",
        "SZjeT"
    ],
    [
        "1:45107",
        "decr"
    ],
    [
        "1:45160",
        "mode"
    ],
    [
        "1:45171",
        "CBC"
    ],
    [
        "1:45200",
        "pad"
    ],
    [
        "1:45241",
        "toString"
    ],
    [
        "1:45260",
        "enc"
    ],
    [
        "1:45271",
        "Utf8"
    ],
    [
        "1:50153",
        "parse"
    ],
    [
        "1:3983",
        "stringify"
    ],
    [
        "1:4045",
        "ujoZe"
    ],
    [
        "1:4100",
        "parse"
    ],
    [
        "1:4155",
        "weNJv"
    ],
    [
        "1:4178",
        "PYpvn"
    ],
    [
        "1:4193",
        "ezTzl"
    ],
    [
        "1:4387",
        "IBWbA"
    ],
    [
        "1:4402",
        "BVhtO"
    ],
    [
        "1:4420",
        "UuDnn"
    ],
    [
        "1:4440",
        "zBbYB"
    ],
    [
        "1:4451",
        "ZBmVd"
    ],
    [
        "1:4884",
        "parse"
    ],
    [
        "1:47371",
        "success"
    ],
    [
        "1:47392",
        "success"
    ],
    [
        "1:50806",
        "iEIcs"
    ]
]);
// let ftosMap = new Map();
async function main(code){
    try {
        // const filename = 'codeTransform.js';
        //
        // // 读取文件
        // const code = await readInputFile(filename);

        // 解析代码为AST
        const ast = parser.parse(code, {
            sourceType: "module"
        })
            
        // 遍历AST 内容有待扩展
        // await traverseAst_Unicode(ast);
        // await traverseAst_进制转换(ast);
        // await traverseAst_字面量变量替换并移除(ast);
        // await traverseAst_字面量运算(ast);
        // await traverseAst_合并对象属性的初始化(ast);
        // await traverseAst_计算可求值的成员表达式(ast);
        // await traverseAst_去除逗号表达式(ast);

        await traverseAst_hook(ast);
        await traverseAst_calc(ast);
    
        // 生成新的代码
        // 对代码进行压缩，以免程序中对代码进行正则检测
        const output = generator(ast, {
            minified: true,
            compact: true,
            comments: false
        }, code);

        // 这段代码的意义是，初始化1个map，然后
        let hookCode = `
        function hookStrFun(funRet, funcallLocation){
            if(!window.ftosMap){
                window.ftosMap = new Map()
            }
            if(!window.ftosMap.has(funcallLocation)){
                window.ftosMap.set(funcallLocation, funRet)
            }
            return funRet
        };
        `
        // 将上面的代码插入到JS代码开头
        output.code = hookCode + output.code +";alert(666)"
    
        // 写入输出文件
        // await writeOutputFile(filename, output.code);
    
        // console.log(`file has been write into : ${path.join(OUTPUT_DIR, filename)}`)

        return output.code
    }catch (e) {
        console.log("发生错误：", e.message())
    }
}


async function traverseAst_hook(ast){
    traverse(ast, {
        // 退出节点的时候被调用
        exit(path){

        },

        // 进入节点的时候被调用
        enter(path){
            // 当类型是 函数调用时 开始处理
            if(type.isCallExpression(path.node)){
                if (
                    // 待处理的第1种类型：只有1个参数，且参数值为 数值型自变量，类似 M[OJ(0x2a3)]
                    (path.node.arguments.length === 1 && type.isNumericLiteral(path.node.arguments[0]))
                    ||
                    // 待处理的第2种类型：有2个参数，第1个是数值型，第2个是字符型，类似 M[R1(0x2fd, 'x3r')]
                    (path.node.arguments.length === 2 && type.isNumericLiteral(path.node.arguments[0]) && type.isStringLiteral(path.node.arguments[1]))
                ){
                    // 这里当函数是 parseInt 时，需要跳过不处理。因为 parseInt 的参数是每次请求都会动态变化的
                    // 这里就还是需要对代码进行有效分析，要不然也得不到正确的结果
                    if (path.parent.type === "CallExpression" && path.parent.callee.name === "parseInt") return

                    // 从 path 里解析出 "行号:列号"，类似 "1:3958"
                    let funcallLocation = path.node.loc.start.line + ":" + path.node.loc.start.column

                    if (ftosMap && ftosMap.has(funcallLocation)){
                        let funRet = ftosMap.get(funcallLocation)
                        let pathBeforeR = path.toString()
                        path.replaceWith(type.valueToNode(funRet))
                        console.log("处理节点替换: ",pathBeforeR, path.toString());
                        path.skip()
                    }else {
                        let callExpression = type.callExpression(
                            type.identifier("hookStrFun"),
                            [
                                path.node,
                                type.stringLiteral(funcallLocation)
                            ]
                        )
                        path.replaceWith(callExpression)
                        console.log("处理节点登记: ", path.toString())
                        path.skip()
                    }
                }
            }
        }
    })
}

async function traverseAst_calc(ast){
    traverse(ast, {
        // exit 是在遍历节点退出的时间点执行
        exit(path){
            if (path.node.type === "BinaryExpression"){
                const left = path.node.left;
                const right = path.node.right;

                // 检查 operand 是否都是字面量
                if (
                    (type.isLiteral(left) ||
                        (type.isUnaryExpression(left) &&
                            type.isLiteral(left.argument)
                        )
                    ) &&
                    (type.isLiteral(right) ||
                        (type.isUnaryExpression(right) &&
                            type.isLiteral(right.argument)
                        )
                    )
                ){
                    let result = eval(path.toString());
                    path.replaceWith(type.valueToNode(result));
                }
            }
        }
    })
}

module.exports = main